# Generated by Django 6.0.4 on 2026-05-12 01:53

from django.db import migrations

def populate_status(apps, schemaeditor):  #Note: The name of function can be anything that is descriptive of their function.  These are python functions.
    entries = {                                         #Here, we are creating a dictionary (analogous to an object). These are the status options we are establishing.
        "published": "A post available for all to view",
        "draft": "A post visible to the author",
        "archived": "An older post visible only to the logged user"
    }
    Status = apps.get_model("posts", "Status")  # This function requires two parameters: the first specifies the applicable app, the second refers to the model class involved.
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)  # We can load Excel data and put that data in the database here.
    ]

